# Enable C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP23=y
CONFIG_EXTERNAL_LIBCPP=y

# Use Newlib
CONFIG_NEWLIB_LIBC=y

# Generic Zephyr settings
CONFIG_GPIO=y

# UART console only - NO USB
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y


# Shell
CONFIG_SHELL=y
CONFIG_DEVICE_SHELL=y

CONFIG_RP2040_BOOTLOADER=y

# Enable HID keyboard module
CONFIG_HID_KEYBOARD=y

# USB Device HID support
CONFIG_USBD_HID_SUPPORT=y
