#!/usr/bin/env python3
"""
Generate a .clangd configuration based on the compile_commands.json.

This script extracts the sysroot and C++ include paths from the first entry
in compile_commands.json and writes a .clangd file that clangd can use.
"""

import json
import os
import re
import sys


def main():
    # Path to compile_commands.json (symlink at project root)
    compile_db = os.path.join(os.path.dirname(__file__), "..", "compile_commands.json")
    if not os.path.exists(compile_db):
        print(f"Error: {compile_db} not found.", file=sys.stderr)
        sys.exit(1)

    with open(compile_db, "r") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error parsing compile_commands.json: {e}", file=sys.stderr)
            sys.exit(1)

    # Find an entry that contains --sysroot
    sysroot = None
    for entry in data:
        cmd = entry.get("command", "")
        # Extract --sysroot value
        match = re.search(r"--sysroot=([^\s]+)", cmd)
        if match:
            sysroot = match.group(1)
            break

    if not sysroot:
        print("Warning: --sysroot not found in compile_commands.json.", file=sys.stderr)
        # Fallback: try to infer from compiler path
        for entry in data:
            compiler = entry.get("command", "").split()[0]
            if "arm-none-eabi" in compiler:
                # Compiler is typically at <sysroot>/../bin/arm-none-eabi-g++
                sysroot = os.path.normpath(
                    os.path.join(compiler, "..", "..", "arm-none-eabi")
                )
                break

    if not sysroot:
        print("Error: Could not determine sysroot.", file=sys.stderr)
        sys.exit(1)

    # Determine C++ include paths (relative to sysroot)
    cxx_include = os.path.join(sysroot, "include", "c++", "14.3.1")
    cxx_include_target = os.path.join(cxx_include, "arm-none-eabi")

    # Write .clangd
    content = f"""# Auto-generated by scripts/generate_clangd.py.
# Do not edit manually.
CompileFlags:
  Add:
    - --query-driver=/nix/store/*/bin/arm-none-eabi-*
    - --sysroot={sysroot}
    - -isystem
    - {cxx_include}
    - -isystem
    - {cxx_include_target}

Diagnostics:
  UnusedIncludes: None

Index:
  Background: Build

CompilationDatabase: build
"""
    with open(".clangd", "w") as f:
        f.write(content)
    print("Generated .clangd")


if __name__ == "__main__":
    main()
