# Enable C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP23=y
CONFIG_EXTERNAL_LIBCPP=y

# Use Newlib
CONFIG_NEWLIB_LIBC=y

# Generic Zephyr settings
CONFIG_GPIO=y
CONFIG_SPI=y

# Monitoring and stuff
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# Playground
CONFIG_SHELL=y
CONFIG_DEVICE_SHELL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# RP2040 Bootloader module
CONFIG_RP2040_BOOTLOADER=y
